Responsive design
HillaryOkello/The-Next-Web-Clone pull request #3
Opened 2020-11-05 16:24 UTC by HillaryOkello

Worked on the mobile view of the website then did the tablet and desktop view. Made sure that the website is responsive on all screen types

2020-11-05 17:07 UTC, euqueme commented
Hello guys :wave: 

I can't start the review because the README file is not descriptive please let's work on it and resubmit for a code review again thank you

- [ ] You should make sure that your repo looks professional before review. Please take a step back and read a lesson here https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/.
Then apply 3 simple rules from this lesson (it will be easy as you can use a template provided there).

This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

2020-11-05 21:15 UTC, MuriloRoque requested changes
## Status: Changes Requested 🔴 

### Hello @HillaryOkello and @Honda99 👋 

### You have started really well, congratulations 👏 

### Please, follow my suggestions so you can improve your project:

## General

- [ ] Please fix your Web hint Linter errors.

- [ ] Your CSS code is repeating a lot of properties, which is considered bad practice since your code gets longer and harder to read. Consider creating classes for the properties you are repeating the most. For example: Create a class called `d-flex`, with the property `display: flex;` and apply this class to all of the elements that are "flexed". Below you can find the number of times you are repeating some properties:

      26 |   display: flex;
      11 |   list-style: none;
      10 |   width: 100%;
       9 |   text-decoration: none;

- [ ] You are using a lot of `!important`, which is also considered a bad practice, you could get lost in your code if you wanted to come back to this project and modify it, so please refactor your code and remove all of the `!important` properties, I know you can do it 💪 

- [ ] I added some comments in your code about another bad practice, which is adding inline-styling. Please refactor those to your CSS, so the styling is only in there 👍 

## Page Structure

**General**

- [ ] There's a horizontal scroll in your page, there must be some element messing up with the width of your page, please fix this so your users have a better experience when visualizing your page 😉 

![horizontal](https://user-images.githubusercontent.com/59691171/98295851-de48d980-1f90-11eb-8960-61b5fde22258.png)


**Header**

***Big Screens***

- [ ] The TNW logo in the header only appears on **medium** screens, you are showing the logo on all screen sizes, please remove it from the **big** screens.

- [ ] The navigation links have a lighter color, yours are too dark when compared with the original.

**Yours:**

![Yours](https://user-images.githubusercontent.com/59691171/98295971-059fa680-1f91-11eb-8d1a-67336fece260.png)


**Original:**

![Original](https://user-images.githubusercontent.com/59691171/98295997-0afcf100-1f91-11eb-97ab-7bf52254a83d.png)


***Medium Screens***

- [ ] The top navigation links should be present on this screen size, yours are vanishing when switching from **big screens** to **medium**.

**Yours:**

![Yours](https://user-images.githubusercontent.com/59691171/98296118-35e74500-1f91-11eb-9722-59196a9f3daa.png)


**Original:**

![Original](https://user-images.githubusercontent.com/59691171/98296124-397acc00-1f91-11eb-8414-abcb7496aab1.png)


**Three Images Section**

***Big Screens***

- [ ] There's a TNW logo inside of the big image to the left on the original page, please try adding it there.

- [x] The font sizes of the text inside of the images on your page are too small compared to the original, please try following the same styling here too 😄 

**Yours:**

![Yours](https://user-images.githubusercontent.com/59691171/98296279-734bd280-1f91-11eb-96e1-a4ee3313d2b1.png)


**Original:**

![Original](https://user-images.githubusercontent.com/59691171/98296295-78108680-1f91-11eb-8be7-9e739aad9707.png)


***Small Screens***

- [ ] Part of the top image is being hidden behind the header, please fix this issue.

**Yours:**
![Yours](https://user-images.githubusercontent.com/59691171/98296462-b7d76e00-1f91-11eb-91ba-cee972c3f704.png)


**Original:**

![Original](https://user-images.githubusercontent.com/59691171/98296471-bc038b80-1f91-11eb-927e-dc90a89da38c.png)


**Latest News Section**

***Big Screens***

- [ ] The images in the second column are positioned too far down compared to the other ones, please try aligning them.

- [ ] This section is too close to the section below it, please try adding some margin between them.

**Yours:**

![Yours](https://user-images.githubusercontent.com/59691171/98296665-01c05400-1f92-11eb-8007-49ec19d8d841.png)


**Original:**

![Original](https://user-images.githubusercontent.com/59691171/98296689-06850800-1f92-11eb-9b46-d79302706512.png)


**Latest Funding Section**

***Big Screens***

- [ ] The title of this section on your page should be aligned to the far left, like in the original.

- [ ] You should have 4 article columns in this section, not 3.

**Yours:**

![Yours](https://user-images.githubusercontent.com/59691171/98296790-346a4c80-1f92-11eb-9e7e-460eb63c75df.png)


**Original:**

![Original](https://user-images.githubusercontent.com/59691171/98296802-38966a00-1f92-11eb-948e-19141303ce1e.png)


***Medium Screens***

- [ ] The links that were aligned to the right on **big screens** should now be aligned below the title on **medium screens**, like the original.

**Yours:**

![Yours](https://user-images.githubusercontent.com/59691171/98296906-654a8180-1f92-11eb-9643-cbfe6143d545.png)


**Original:**

![Original](https://user-images.githubusercontent.com/59691171/98296923-69769f00-1f92-11eb-8a42-db6ccb092287.png)


**Hard Fork, Apps, Gear Section**

***Big screens***

- [ ] This section is not aligned to the middle, like the original.

**Yours:**

![Yours](https://user-images.githubusercontent.com/59691171/98297045-99be3d80-1f92-11eb-927c-dde09a13cc73.png)


**Original:**

![Original](https://user-images.githubusercontent.com/59691171/98297056-9dea5b00-1f92-11eb-8bfe-b0ab6f6d7c02.png)

## Summary

- The code is good overall, there are just some minor issues to fix 😄 
- Your repository is very professional, keep up the good work 💪 
- There are only some issues to solve and then we can move on 🚀 

Kindly make the requested changes and submit for another review, please :pray: 

I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-11-05 21:15 UTC, MuriloRoque commented on index.html
> +                <a href="#" class="back" style="background-image: url(./images/latest\ 3.jpg);"></a>
- [ ] Please remove the `style` property from the element, let's do this in our CSS?

2020-11-05 21:15 UTC, MuriloRoque commented on index.html
> +                <a href="#" class="back" style="background-image: url(./images/latest\ 2.jpg);"></a>
- [ ]  Please remove the style property from the element, let's do this in our CSS?

2020-11-05 21:15 UTC, MuriloRoque commented on index.html
> +                <a href="#" class="back" style="background-image: url(./images/voted.png);"></a>
- [ ]  Please remove the style property from the element, let's do this in our CSS?

2020-11-05 21:15 UTC, MuriloRoque commented on index.html
> +                <a href="#" class="back" style="background-image: url(./images/twitter-engineer.png);"></a>
- [ ]  Please remove the style property from the element, let's do this in our CSS?

2020-11-05 21:15 UTC, MuriloRoque commented on index.html
> +                <a href="#" class="back" style="background-image: url(./images/Tesla-supercharger-europe-germany-car-future-EV-charging-free-796x448.jpg);"></a>
- [ ]  Please remove the style property from the element, let's do this in our CSS?

2020-11-05 21:15 UTC, MuriloRoque commented on index.html
> +                <a href="#" class="back" style="background-image: url(./images/Degoo-Lifestyle-540x270.jpg);"></a>
- [ ]  Please remove the style property from the element, let's do this in our CSS?

2020-11-05 21:15 UTC, MuriloRoque commented on index.html
> +                <a href="#" class="back" style="background-image: url(./images/cloud.jpg);"></a>
- [ ]  Please remove the style property from the element, let's do this in our CSS?

2020-11-05 21:15 UTC, MuriloRoque commented on index.html
> +                <a href="#" class="back" style="background-image: url(./images/circuit.png);"></a>
- [ ]  Please remove the style property from the element, let's do this in our CSS?

2020-11-05 21:15 UTC, MuriloRoque commented on index.html
> +            <div class="grid" style="background-image: url(./images/Hardfork.jpg);">
- [ ]  Please remove the style property from the element, let's do this in our CSS?

2020-11-05 21:15 UTC, MuriloRoque commented on index.html
> +            <div class="grid" style="background-image: url(./images/Messenger-Image.jpg);">
- [ ]  Please remove the style property from the element, let's do this in our CSS?

2020-11-05 21:15 UTC, MuriloRoque commented on index.html
> +            <div class="grid" style="background-image: url(./images/gear.png);">
- [ ]  Please remove the style property from the element, let's do this in our CSS?

2020-11-05 21:15 UTC, MuriloRoque commented on index.html
> +            <div class="grid" style="background-image: url(./images/card-v-card-bank-account-multiplayer-game.png);">
- [ ]  Please remove the style property from the element, let's do this in our CSS?

2020-11-05 21:15 UTC, MuriloRoque commented on index.html
> +            <div class="grid" style="background-image: url(./images/creative.jpg);">
- [ ]  Please remove the style property from the element, let's do this in our CSS?

2020-11-05 21:15 UTC, MuriloRoque commented on index.html
> +            <div class="grid" style="background-image: url(./images/google-logo-podium-368x276.png);">
- [ ]

2020-11-05 21:15 UTC, MuriloRoque commented on index.html
> +            <div class="grid" style="background-image: url(./images/Netflix-Blur-vibration-haptic-feedback-project-rumble-pak-368x276.jpg);">
- [ ]  Please remove the style property from the element, let's do this in our CSS?

2020-11-05 21:15 UTC, MuriloRoque commented on index.html
> +            <div class="grid" style="background-image: url(./images/Distract.jpeg);">
- [ ]  Please remove the style property from the element, let's do this in our CSS?

2020-11-05 21:15 UTC, MuriloRoque commented on index.html
> +              <a href="#" class="back" style="background-image: url(./images/deals1.jpg);"></a>
- [ ]  Please remove the style property from the element, let's do this in our CSS?

2020-11-05 21:15 UTC, MuriloRoque commented on index.html
> +              <a href="#" class="back" style="background-image: url(./images/deals2.jpg);"></a>
- [ ]  Please remove the style property from the element, let's do this in our CSS?

2020-11-05 21:15 UTC, MuriloRoque commented on index.html
> +              <a href="#" class="back" style="background-image: url(./images/deals3.jpg);"></a>
- [ ]  Please remove the style property from the element, let's do this in our CSS?

2020-11-05 21:15 UTC, MuriloRoque commented on index.html
> +              <a href="#" class="back" style="background-image: url(./images/deals5.jpg);"></a>
- [ ]  Please remove the style property from the element, let's do this in our CSS?

2020-11-05 21:15 UTC, MuriloRoque commented on index.html
> +              <a href="#" class="back" style="background-image: url(./images/deals6.jpg);"></a>
- [ ]  Please remove the style property from the element, let's do this in our CSS?

2020-11-05 21:15 UTC, MuriloRoque commented on index.html
> +              <a href="#" class="back" style="background-image: url(./images/deals7.jpg);"></a>
- [ ]  Please remove the style property from the element, let's do this in our CSS?

2020-11-05 21:15 UTC, MuriloRoque commented on index.html
> +              <a href="#" class="back" style="background-image: url(./images/deals8.jpg"></a>
- [ ]  Please remove the style property from the element, let's do this in our CSS?

2020-11-06 20:30 UTC, uche-inyama requested changes
## Changes Required

### Hi team :wave: 

 Good work and great effort so far  :slightly_smiling_face: 

However, there are some designs that need to be edited, on your webpage.

### Header

Medium Screens
 
The top navigation links should be present on this screen size, yours are vanishing when switching from big screens to medium. Just as the last TSE pointed out.

### Latest News Section

Big Screens

 The images in the third column are not positioned properly. Compare them with the original website and make the necessary changes.

### Apps, Gears & Tech section

Medium screen 

@media >= 768px, Apps, Gear, Tech should be a grid with three columns; yours is a single column kindly reference the [main](https://thenextweb.com/) website.

[**Observation**] Please take your time to compare the [TNW](https://thenextweb.com/) with the **cloned** site you have designed. View it using chrome developer tools at a lower percentage, like 50%.  You would have a better perspective of the things you need to modify.

#### That is it, make the necessary changes, then submit another form for a code review.

If you need clarifications, do reach out on slack.

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama```

2020-11-06 20:41 UTC, uche-inyama commented on index.html
> +            <div class="grid" style="background-image: url(./images/Hardfork.jpg);">
Please remove all the inline style you have in your HTML file

2020-11-07 10:25 UTC, MuriloRoque approved these changes
## Status: Approved :green_circle: 

### Hello again @HillaryOkello :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-11-07 11:04 UTC, merged